namespace: fts3-db

resources:
  - ns.yaml
  - mariadb-cluster.yaml
  
  #- fts3-database.yaml
  # - service.yaml
  #- fts3-instance.yaml
  #- fts3-grant.yaml
  #- fts3-user.yaml
  #- mariadb-cm.yaml

secretGenerator:
  - name: mariadb-root
    options:
      disableNameSuffixHash: true
    files:
    - password=etc/secrets/fts3db-root-password
  - name: mariadb-user
    options:
      disableNameSuffixHash: true
    files:
    - password=etc/secrets/fts3db-fts3-password
    - username=etc/secrets/fts3db-username