apiVersion: batch/v1
kind: CronJob
metadata:
  name: fetch-crl-cron
spec:
  concurrencyPolicy: Replace
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - args:
            name: fetch-crl
            image: docker.io/bjwhitefnal/fetch-crl-cron:latest
            imagePullPolicy: Always
            volumeMounts:
            - name: grid-certificates
              mountPath: /out/
          restartPolicy: OnFailure
          terminationGracePeriodSeconds: 30
          volumes:
          - name: grid-certificates
            persistentVolumeClaim:
              claimName: grid-certificates-pvc
  schedule: "0 */3 * * *"
  suspend: false
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: fts3-log-cleanup
spec:
  schedule: "45 3 * * *" # Runs daily 0345
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: log-cleanup
            image: docker.io/bjwhitefnal/fts3-al9
            command: ["/bin/sh", "-c", "find /logs/fts3/transfers -mtime +14 -exec rm -rv {} +"]
            volumeMounts:
            - name: fts3-logs
              mountPath: /logs
          restartPolicy: OnFailure
          volumes:
          - name: fts3-logs
            persistentVolumeClaim:
              claimName: fts3-logs-pvc