---
# Source: mariadb-operator/templates/webhook/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: release-name-mariadb-operator-webhook
  labels:
    helm.sh/chart: mariadb-operator-0.38.1
    app.kubernetes.io/name: mariadb-operator-webhook
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "0.38.1"
    app.kubernetes.io/managed-by: Helm
