apiVersion: batch/v1
kind: CronJob
metadata:
  name: fetch-crl-cron
spec:
  concurrencyPolicy: Replace
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - args:
            name: fetch-crl
            image: docker.io/bjwhitefnal/fetch-crl-cron:latest
            imagePullPolicy: Always
            volumeMounts:
            - name: grid-certificates
              mountPath: /out/
          restartPolicy: OnFailure
          terminationGracePeriodSeconds: 30
          volumes:
          - name: grid-certificates
            persistentVolumeClaim:
              claimName: grid-certificates-pvc
  schedule: "0 */3 * * *"
  suspend: false