apiVersion: v1
kind: Service
metadata:
  name: fts3
  labels:
    app: fts3
  namespace: fts3
  annotations:
    metallb.universe.tf/address-pool: sdf-dmz
    metallb.universe.tf/loadBalancerIPs: 134.79.23.193
spec:
  type: LoadBalancer
  ports:
    - port: 8446
      targetPort: 8446
      protocol: TCP
      name: fts3-rest
    - port: 8449
      targetPort: 8449
      protocol: TCP
      name: fts3-mon
  selector:
    app: fts3
