---
# Source: mariadb-operator/templates/operator/rbac-user.yaml
# the mariadb-view ClusterRole allows viewing all k8s.mariadb.com resources
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: release-name-mariadb-operator-view
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: "true"
rules:
- apiGroups: ["k8s.mariadb.com"]
  resources: ["*"]
  verbs: ["get", "list", "watch"]
---
# Source: mariadb-operator/templates/operator/rbac-user.yaml
# the mariadb-edit ClusterRole allows editing k8s.mariadb.com resources
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: release-name-mariadb-operator-edit
  labels:
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
rules:
- apiGroups: ["k8s.mariadb.com"]
  resources: ["*"]
  verbs: ["create", "update", "patch", "delete"]
