---
# Source: mariadb-operator/templates/cert-controller/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: release-name-mariadb-operator-cert-controller
rules:
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - validatingwebhookconfigurations
  - mutatingwebhookconfigurations
  verbs:
  - get
  - list
  - update
  - patch
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - list
  - patch
  - watch
- apiGroups:
  - ""
  resources:
  - endpoints
  - endpoints/restricted
  verbs:
  - get
  - list
  - watch
---
# Source: mariadb-operator/templates/cert-controller/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: release-name-mariadb-operator-cert-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: release-name-mariadb-operator-cert-controller
subjects:
- kind: ServiceAccount
  name: release-name-mariadb-operator-cert-controller-cert-controller
  namespace: mariadb-operator
---
# Source: mariadb-operator/templates/cert-controller/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: release-name-mariadb-operator-cert-controller
rules:
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
# Source: mariadb-operator/templates/cert-controller/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: release-name-mariadb-operator-cert-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: release-name-mariadb-operator-cert-controller
subjects:
- kind: ServiceAccount
  name: release-name-mariadb-operator-cert-controller-cert-controller
  namespace: mariadb-operator
